import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Nav from "@/components/shared/Nav";
import Footer from "@/components/shared/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nike Shoes Products",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        {children}
        <section className="bg-black padding-x padding-t pb-8">
          <Footer />
        </section>
      </body>
    </html>
  );
}
